Repository LucasRejanio/novato-dev, pull requests merged in 2021-05, with the labels that each got.

#14 Release semana 10-05-2021
  .github/workflows/deploy.yml
  main.py
  modulos/__init__.py
  modulos/comandos/main.py
  modulos/comandos/respostas/__init__.py
  modulos/comandos/respostas/explicacoes.py
  modulos/comandos/respostas/java.py
  modulos/comandos/respostas/javascript.py
  modulos/comandos/respostas/python.py
  modulos/comandos/respostas/tratamento.py
Labels: release

#18 Release semana 17-05-2021
  .pylintrc
  README.md
  main.py
  modulos/comandos/main.py
  modulos/comandos/respostas/explicacoes.py
  modulos/comandos/respostas/java.py
  modulos/comandos/respostas/javascript.py
  modulos/comandos/respostas/python.py
  modulos/comandos/respostas/tratamento.py
Labels: release

#21 Release semana 24 05 2021
  main.py
  modulos/comandos/aprendizagem.py
  modulos/comandos/main.py
  modulos/comandos/respostas/aprendizagem/__init__.py
  modulos/comandos/respostas/aprendizagem/explicacoes.py
  modulos/comandos/respostas/aprendizagem/java.py
  modulos/comandos/respostas/aprendizagem/javascript.py
  modulos/comandos/respostas/aprendizagem/python.py
  modulos/comandos/respostas/teste/__init__.py
  modulos/comandos/respostas/teste/perguntas.py
  modulos/comandos/respostas/tratamento.py
  modulos/comandos/teste.py
  modulos/comandos/utils.py
Labels: release

#24 Ajustes finais no bot
  modulos/comandos/aprendizagem.py
  modulos/comandos/main.py
  modulos/comandos/respostas/utils.py
  video.txt
Labels: feature

#25 Release semana 30 05 2021
  modulos/comandos/aprendizagem.py
  modulos/comandos/main.py
  modulos/comandos/respostas/utils.py
  video.txt
Labels: release

#26 Colocando conteúdo no desenvolvimento
  README.md
Labels: documentation
